# Generated by Django 2.2.16 on 2020-09-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiped',
            name='stime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='滑动时间'),
        ),
    ]
