# Generated by Django 2.2.16 on 2020-09-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(max_length=11)),
                ('nickname', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[('boy', '男'), ('girl', '女')], max_length=6)),
                ('birthday', models.DateField(default='2010-01-01')),
                ('avatar', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
