# Generated by Django 2.2.16 on 2020-09-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_location', models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('深圳', '深圳'), ('成都', '成都'), ('西安', '西安'), ('武汉', '武汉'), ('沈阳', '沈阳')], max_length=10, verbose_name='⽬标城市')),
                ('dating_gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=10, verbose_name='匹配的性别')),
                ('min_distance', models.IntegerField(default=1, verbose_name='最⼩查找范围')),
                ('max_distance', models.IntegerField(default=50, verbose_name='最⼤查找范围')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='最⼩交友年龄')),
                ('max_dating_age', models.IntegerField(default=50, verbose_name='最⼤交友年龄')),
                ('vibration', models.BooleanField(default=True, verbose_name='开启震动')),
                ('only_matched', models.BooleanField(default=True, verbose_name='不让陌⽣⼈看我的相册')),
                ('auto_play', models.BooleanField(default=True, verbose_name='⾃动播放视频')),
            ],
        ),
    ]
