# Generated by Django 2.2.16 on 2020-09-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('boy', '男'), ('girl', '女')], default='boy', max_length=6),
        ),
    ]
